/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;
import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.wavemaker.runtime.data.dao.query.WMQueryExecutor;
import com.wavemaker.runtime.data.export.ExportOptions;
import com.wavemaker.runtime.data.model.QueryProcedureInput;

import com.hrdb.models.query.*;

@Service
public class HrdbQueryExecutorServiceImpl_V1 implements HrdbQueryExecutorService_V1 {

    private static final Logger LOGGER = LoggerFactory.getLogger(HrdbQueryExecutorServiceImpl.class);

    @Autowired
    @Qualifier("hrdbWMQueryExecutor")
    private WMQueryExecutor queryExecutor;

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeNoOfEmployee(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("NoOfEmployee", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSelectedEmployeeID(Pageable pageable, Integer data) {
        Map params = new HashMap(1);

        params.put("data", data);

        return queryExecutor.executeNamedQuery("SelectedEmployeeID", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeNoOfDepartments(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("noOfDepartments", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeEngineeringEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("EngineeringEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeProfessionalServicesEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("ProfessionalServicesEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeSalesEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("SalesEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeGeneralAndAdminEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("GeneralAndAdminEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeMarketingEmployees(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("MarketingEmployees", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeNoOfDepartment(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("NoOfDepartment", params, Object.class, pageable);
    }

    @Transactional(value = "hrdbTransactionManager", readOnly = true)
    @Override
    public Page<Object> executeTotalBudget(Pageable pageable) {
        Map params = new HashMap(0);


        return queryExecutor.executeNamedQuery("TotalBudget", params, Object.class, pageable);
    }

}