/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<NoOfEmployeeResponse> executeNoOfEmployee(Pageable pageable);

    void exportNoOfEmployee(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SelectedEmployeeIdResponse> executeSelectedEmployeeID(Integer data, Pageable pageable);

    void exportSelectedEmployeeID(Integer data, ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<NoOfDepartmentsResponse> executeNoOfDepartments(Pageable pageable);

    void exportNoOfDepartments(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<EngineeringEmployeesResponse> executeEngineeringEmployees(Pageable pageable);

    void exportEngineeringEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<ProfessionalServicesEmployeesResponse> executeProfessionalServicesEmployees(Pageable pageable);

    void exportProfessionalServicesEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<SalesEmployeesResponse> executeSalesEmployees(Pageable pageable);

    void exportSalesEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GeneralAndAdminEmployeesResponse> executeGeneralAndAdminEmployees(Pageable pageable);

    void exportGeneralAndAdminEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<MarketingEmployeesResponse> executeMarketingEmployees(Pageable pageable);

    void exportMarketingEmployees(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<NoOfDepartmentResponse> executeNoOfDepartment(Pageable pageable);

    void exportNoOfDepartment(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<TotalBudgetResponse> executeTotalBudget(Pageable pageable);

    void exportTotalBudget(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}