/*\/**
 * Copyright (c) 2015-2016 wavemaker.com All Rights Reserved.
 * This software is the confidential and proprietary information of wavemaker-com * You shall not disclose such Confidential Information and shall use it only in accordance
 * with the terms of the source code license agreement you entered into with wavemaker.com *\/*/
package com.hrdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class MarketingEmployeesResponse implements Serializable {


    @JsonProperty("PICURL")
    @ColumnAlias("PICURL")
    private String picurl;

    @JsonProperty("FIRSTNAME")
    @ColumnAlias("FIRSTNAME")
    private String firstname;

    @JsonProperty("STATE")
    @ColumnAlias("STATE")
    private String state;

    @JsonProperty("ZIP")
    @ColumnAlias("ZIP")
    private String zip;

    @JsonProperty("BIRTHDATE")
    @ColumnAlias("BIRTHDATE")
    private Date birthdate;

    @JsonProperty("TENANTID")
    @ColumnAlias("TENANTID")
    private Integer tenantid;

    @JsonProperty("EID")
    @ColumnAlias("EID")
    private Integer eid;

    @JsonProperty("CITY")
    @ColumnAlias("CITY")
    private String city;

    @JsonProperty("STREET")
    @ColumnAlias("STREET")
    private String street;

    @JsonProperty("JOBTITLE")
    @ColumnAlias("JOBTITLE")
    private String jobtitle;

    @JsonProperty("DEPTID")
    @ColumnAlias("DEPTID")
    private Integer deptid;

    @JsonProperty("MANAGERID")
    @ColumnAlias("MANAGERID")
    private String managerid;

    @JsonProperty("LASTNAME")
    @ColumnAlias("LASTNAME")
    private String lastname;

    public String getPicurl() {
        return this.picurl;
    }

    public void setPicurl(String picurl) {
        this.picurl = picurl;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Date getBirthdate() {
        return this.birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public Integer getTenantid() {
        return this.tenantid;
    }

    public void setTenantid(Integer tenantid) {
        this.tenantid = tenantid;
    }

    public Integer getEid() {
        return this.eid;
    }

    public void setEid(Integer eid) {
        this.eid = eid;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getJobtitle() {
        return this.jobtitle;
    }

    public void setJobtitle(String jobtitle) {
        this.jobtitle = jobtitle;
    }

    public Integer getDeptid() {
        return this.deptid;
    }

    public void setDeptid(Integer deptid) {
        this.deptid = deptid;
    }

    public String getManagerid() {
        return this.managerid;
    }

    public void setManagerid(String managerid) {
        this.managerid = managerid;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MarketingEmployeesResponse)) return false;
        final MarketingEmployeesResponse marketingEmployeesResponse = (MarketingEmployeesResponse) o;
        return Objects.equals(getPicurl(), marketingEmployeesResponse.getPicurl()) &&
                Objects.equals(getFirstname(), marketingEmployeesResponse.getFirstname()) &&
                Objects.equals(getState(), marketingEmployeesResponse.getState()) &&
                Objects.equals(getZip(), marketingEmployeesResponse.getZip()) &&
                Objects.equals(getBirthdate(), marketingEmployeesResponse.getBirthdate()) &&
                Objects.equals(getTenantid(), marketingEmployeesResponse.getTenantid()) &&
                Objects.equals(getEid(), marketingEmployeesResponse.getEid()) &&
                Objects.equals(getCity(), marketingEmployeesResponse.getCity()) &&
                Objects.equals(getStreet(), marketingEmployeesResponse.getStreet()) &&
                Objects.equals(getJobtitle(), marketingEmployeesResponse.getJobtitle()) &&
                Objects.equals(getDeptid(), marketingEmployeesResponse.getDeptid()) &&
                Objects.equals(getManagerid(), marketingEmployeesResponse.getManagerid()) &&
                Objects.equals(getLastname(), marketingEmployeesResponse.getLastname());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getPicurl(),
                getFirstname(),
                getState(),
                getZip(),
                getBirthdate(),
                getTenantid(),
                getEid(),
                getCity(),
                getStreet(),
                getJobtitle(),
                getDeptid(),
                getManagerid(),
                getLastname());
    }
}